---
require: rubocop-rspec

AllCops:
  Include:
  - '**/Rakefile'
  - 'rakelib/**/*'
  Exclude:
  - 'build/**/*'
  - Gemfile
Layout/EmptyLinesAroundBlockBody:
  Exclude:
  - 'spec/**/*.rb'
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
Layout/MultilineOperationIndentation:
  Enabled: false
Metrics/AbcSize:
 Max: 22
Metrics/BlockLength:
  Exclude:
  - 'spec/**/*.rb'
Metrics/ClassLength:
  Max: 250
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 25
Metrics/ParameterLists:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Naming/UncommunicativeMethodParamName:
  Enabled: false
RSpec/ExampleLength:
  Max: 20
RSpec/AnyInstance:
  Enabled: false
RSpec/ExpectOutput:
  Enabled: false
RSpec/FilePath:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NestedGroups:
  Max: 4
Security/Open:
  Enabled: false # False positive at the moment
Style/Documentation:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/MethodMissing:
  Enabled: false
