#!/usr/bin/env ruby
# Cloud Foundry Java Buildpack
# Copyright (c) 2013 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

require 'time'

$stdout.sync = true

module Kill

  def Kill.log(log_title, log_data)
    log_file = "#{File.dirname(__FILE__)}/buildpack.log"
    File.open(log_file, 'a') do |log_file|
      log_file.write "#{log_title} @ #{Kill.time_in_millis}::\n"
      log_file.write(log_data)
    end
  end

  def Kill.time_in_millis
    Time.now.xmlschema(3).sub(/T/, ' ')
  end

end

begin
  Kill.log("#{__FILE__} attempting to kill Java processes",
           `pkill -9 -f .*-XX:OnOutOfMemoryError=.*#{File.basename(__FILE__)}`)
rescue => e
  Kill.log("#{__FILE__} failed with exception", "#{e.inspect}, #{e.backtrace}\n")
  abort e.message
end

