#!/usr/bin/env ruby
# Encoding: utf-8
# Cloud Foundry Java Buildpack
# Copyright (c) 2013 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Kill script for use as the parameter of OpenJDK's -XX:OnOutOfMemoryError.
#
# It should be placed in the buildpack diagnostic directory so it logs to
# the same log file as the rest of the buildpack.

require 'time'

$stdout.sync = true

module Kill

  def self.log(log_data)
    log_file_name = "#{File.dirname(__FILE__)}/@@LOG_FILE_NAME@@"
    File.open(log_file_name, 'a') do |log_file|
      log_file.sync = true
      log_file.write "#{log_data} @ #{Kill.time_in_millis}\n"
      log_file.fsync
    end
  end

  def self.time_in_millis
    Time.now.xmlschema(3).sub(/T/, ' ')
  end

  def self.log_process_tree
    Kill.log(`ps -AHF`)
  end

end

begin
  Kill.log_process_tree
  # Kill all processes whose parameters match -XX:OnOutOfMemoryError and the name of this script.
  # This script can be renamed as necessary without modifying its code.
  command = "pkill -9 -f .*-XX:OnOutOfMemoryError=.*#{File.basename(__FILE__)}.*"
  Kill.log("#{__FILE__} attempting to kill Java processes using `#{command}`")
  system command
  Kill.log_process_tree
rescue => e
  Kill.log("#{__FILE__} failed with exception #{e.inspect}, #{e.backtrace}\n")
  abort e.message
end
