package frameworks_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/cloudfoundry/java-buildpack/src/java/resources"
)

// TestNewRelicEmbeddedConfigExists tests that the newrelic.yml file
// exists in the embedded resources
func TestNewRelicEmbeddedConfigExists(t *testing.T) {
	// Check if the embedded resource exists
	embeddedPath := "new_relic_agent/newrelic.yml"

	exists := resources.Exists(embeddedPath)
	if !exists {
		t.Fatalf("Expected embedded resource '%s' to exist", embeddedPath)
	}
}

// TestNewRelicEmbeddedConfigContent tests that the embedded newrelic.yml
// has the expected ERB placeholders and structure
func TestNewRelicEmbeddedConfigContent(t *testing.T) {
	embeddedPath := "new_relic_agent/newrelic.yml"

	// Read the embedded resource
	configData, err := resources.GetResource(embeddedPath)
	if err != nil {
		t.Fatalf("Failed to read embedded newrelic.yml: %v", err)
	}

	configStr := string(configData)

	// Verify ERB placeholders are present (these should be replaced during deployment)
	if !strings.Contains(configStr, "<%= generated_for_user %>") {
		t.Error("Expected ERB placeholder '<%= generated_for_user %>' to be present in embedded config")
	}

	if !strings.Contains(configStr, "<%= license_key %>") {
		t.Error("Expected ERB placeholder '<%= license_key %>' to be present in embedded config")
	}

	// Verify config structure
	if !strings.Contains(configStr, "common: &default_settings") {
		t.Error("Expected YAML structure 'common: &default_settings' in config")
	}

	// Verify key configuration sections
	expectedSections := []string{
		"license_key:",
		"agent_enabled:",
		"app_name:",
		"transaction_tracer:",
		"error_collector:",
		"distributed_tracing:",
	}

	for _, section := range expectedSections {
		if !strings.Contains(configStr, section) {
			t.Errorf("Expected configuration section '%s' in newrelic.yml", section)
		}
	}
}

// TestNewRelicConfigDeploymentProcessing tests that ERB placeholders
// are correctly replaced when the config is deployed
func TestNewRelicConfigDeploymentProcessing(t *testing.T) {
	embeddedPath := "new_relic_agent/newrelic.yml"

	// Read the embedded resource
	configData, err := resources.GetResource(embeddedPath)
	if err != nil {
		t.Fatalf("Failed to read embedded newrelic.yml: %v", err)
	}

	// Simulate what the framework does: replace ERB placeholders
	configStr := string(configData)

	// Replace <%= generated_for_user %> with buildpack info
	configStr = strings.ReplaceAll(configStr, "<%= generated_for_user %>",
		"This configuration file was generated by the Cloud Foundry Java Buildpack")

	// Replace <%= license_key %> with placeholder
	configStr = strings.ReplaceAll(configStr, "<%= license_key %>", "YOUR_LICENSE_KEY_HERE")

	// Verify replacements worked
	if strings.Contains(configStr, "<%= generated_for_user %>") {
		t.Error("ERB placeholder '<%= generated_for_user %>' was not replaced")
	}

	if strings.Contains(configStr, "<%= license_key %>") {
		t.Error("ERB placeholder '<%= license_key %>' was not replaced")
	}

	// Verify replacement values are present
	if !strings.Contains(configStr, "This configuration file was generated by the Cloud Foundry Java Buildpack") {
		t.Error("Expected buildpack generation message after replacement")
	}

	if !strings.Contains(configStr, "license_key: 'YOUR_LICENSE_KEY_HERE'") {
		t.Error("Expected processed license_key line with placeholder")
	}

	// Verify config is still valid YAML structure
	if !strings.Contains(configStr, "common: &default_settings") {
		t.Error("YAML structure was corrupted during processing")
	}
}

// TestNewRelicConfigFileCreation tests the full workflow of reading
// embedded config and writing it to disk
func TestNewRelicConfigFileCreation(t *testing.T) {
	// Create a temporary directory for testing
	tmpDir, err := os.MkdirTemp("", "newrelic-test-*")
	if err != nil {
		t.Fatalf("Failed to create temp dir: %v", err)
	}
	defer os.RemoveAll(tmpDir)

	// Create agent directory
	agentDir := filepath.Join(tmpDir, "new_relic_agent")
	if err := os.MkdirAll(agentDir, 0755); err != nil {
		t.Fatalf("Failed to create agent directory: %v", err)
	}

	// Read embedded config
	embeddedPath := "new_relic_agent/newrelic.yml"
	configData, err := resources.GetResource(embeddedPath)
	if err != nil {
		t.Fatalf("Failed to read embedded config: %v", err)
	}

	// Process template
	configStr := string(configData)
	configStr = strings.ReplaceAll(configStr, "<%= generated_for_user %>",
		"This configuration file was generated by the Cloud Foundry Java Buildpack")
	configStr = strings.ReplaceAll(configStr, "<%= license_key %>", "YOUR_LICENSE_KEY_HERE")

	// Write to disk
	configPath := filepath.Join(agentDir, "newrelic.yml")
	if err := os.WriteFile(configPath, []byte(configStr), 0644); err != nil {
		t.Fatalf("Failed to write config file: %v", err)
	}

	// Verify file was created
	if _, err := os.Stat(configPath); os.IsNotExist(err) {
		t.Error("Config file was not created")
	}

	// Read back and verify content
	writtenData, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("Failed to read written config: %v", err)
	}

	writtenStr := string(writtenData)

	// Verify content integrity
	if !strings.Contains(writtenStr, "common: &default_settings") {
		t.Error("Written config is missing expected YAML structure")
	}

	if !strings.Contains(writtenStr, "This configuration file was generated by the Cloud Foundry Java Buildpack") {
		t.Error("Written config is missing buildpack generation message")
	}

	if !strings.Contains(writtenStr, "license_key: 'YOUR_LICENSE_KEY_HERE'") {
		t.Error("Written config is missing processed license key")
	}

	// Verify ERB placeholders are gone
	if strings.Contains(writtenStr, "<%=") {
		t.Error("Written config still contains ERB placeholders")
	}
}

// TestNewRelicConfigSkipIfExists tests that existing config is not overwritten
func TestNewRelicConfigSkipIfExists(t *testing.T) {
	// Create a temporary directory
	tmpDir, err := os.MkdirTemp("", "newrelic-test-*")
	if err != nil {
		t.Fatalf("Failed to create temp dir: %v", err)
	}
	defer os.RemoveAll(tmpDir)

	agentDir := filepath.Join(tmpDir, "new_relic_agent")
	if err := os.MkdirAll(agentDir, 0755); err != nil {
		t.Fatalf("Failed to create agent directory: %v", err)
	}

	// Create a user-provided config FIRST
	configPath := filepath.Join(agentDir, "newrelic.yml")
	userConfig := "# User-provided configuration\nlicense_key: 'my-custom-key'\n"
	if err := os.WriteFile(configPath, []byte(userConfig), 0644); err != nil {
		t.Fatalf("Failed to create user config: %v", err)
	}

	// Simulate the framework's check: if file exists, skip installation
	if _, err := os.Stat(configPath); err == nil {
		// File exists, skip - this is what the framework does
		t.Log("Config already exists, skipping installation (as expected)")
	} else {
		t.Error("Should have detected existing config file")
	}

	// Verify the user config is still intact
	existingData, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("Failed to read existing config: %v", err)
	}

	existingStr := string(existingData)
	if !strings.Contains(existingStr, "# User-provided configuration") {
		t.Error("User-provided config was modified")
	}

	if !strings.Contains(existingStr, "my-custom-key") {
		t.Error("User-provided license key was lost")
	}
}
