package frameworks_test

import (
	"os"
	"path/filepath"
	"strings"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	"github.com/cloudfoundry/java-buildpack/src/java/resources"
)

var _ = Describe("NewRelicAgent", func() {
	var embeddedPath string

	BeforeEach(func() {
		embeddedPath = "new_relic_agent/newrelic.yml"
	})

	It("should have embedded config file", func() {
		exists := resources.Exists(embeddedPath)
		Expect(exists).To(BeTrue(), "Expected embedded resource '%s' to exist", embeddedPath)
	})

	It("should have ERB placeholders and config structure", func() {
		configData, err := resources.GetResource(embeddedPath)
		Expect(err).NotTo(HaveOccurred())

		configStr := string(configData)

		Expect(configStr).To(ContainSubstring("<%= generated_for_user %>"))
		Expect(configStr).To(ContainSubstring("<%= license_key %>"))
		Expect(configStr).To(ContainSubstring("common: &default_settings"))

		expectedSections := []string{
			"license_key:",
			"agent_enabled:",
			"app_name:",
			"transaction_tracer:",
			"error_collector:",
			"distributed_tracing:",
		}

		for _, section := range expectedSections {
			Expect(configStr).To(ContainSubstring(section), "Expected configuration section '%s' in newrelic.yml", section)
		}
	})

	It("should correctly replace ERB placeholders", func() {
		configData, err := resources.GetResource(embeddedPath)
		Expect(err).NotTo(HaveOccurred())

		configStr := string(configData)
		configStr = strings.ReplaceAll(configStr, "<%= generated_for_user %>",
			"This configuration file was generated by the Cloud Foundry Java Buildpack")
		configStr = strings.ReplaceAll(configStr, "<%= license_key %>", "YOUR_LICENSE_KEY_HERE")

		Expect(configStr).NotTo(ContainSubstring("<%= generated_for_user %>"))
		Expect(configStr).NotTo(ContainSubstring("<%= license_key %>"))
		Expect(configStr).To(ContainSubstring("This configuration file was generated by the Cloud Foundry Java Buildpack"))
		Expect(configStr).To(ContainSubstring("license_key: 'YOUR_LICENSE_KEY_HERE'"))
		Expect(configStr).To(ContainSubstring("common: &default_settings"))
	})

	Context("config file creation", func() {
		var tmpDir string
		var agentDir string

		BeforeEach(func() {
			var err error
			tmpDir, err = os.MkdirTemp("", "newrelic-test-*")
			Expect(err).NotTo(HaveOccurred())
			agentDir = filepath.Join(tmpDir, "new_relic_agent")
		})

		AfterEach(func() {
			os.RemoveAll(tmpDir)
		})

		It("should create config file from embedded resource", func() {
			err := os.MkdirAll(agentDir, 0755)
			Expect(err).NotTo(HaveOccurred())

			configData, err := resources.GetResource(embeddedPath)
			Expect(err).NotTo(HaveOccurred())

			configStr := string(configData)
			configStr = strings.ReplaceAll(configStr, "<%= generated_for_user %>",
				"This configuration file was generated by the Cloud Foundry Java Buildpack")
			configStr = strings.ReplaceAll(configStr, "<%= license_key %>", "YOUR_LICENSE_KEY_HERE")

			configPath := filepath.Join(agentDir, "newrelic.yml")
			err = os.WriteFile(configPath, []byte(configStr), 0644)
			Expect(err).NotTo(HaveOccurred())

			Expect(configPath).To(BeARegularFile())

			writtenData, err := os.ReadFile(configPath)
			Expect(err).NotTo(HaveOccurred())

			writtenStr := string(writtenData)
			Expect(writtenStr).To(ContainSubstring("common: &default_settings"))
			Expect(writtenStr).To(ContainSubstring("This configuration file was generated by the Cloud Foundry Java Buildpack"))
			Expect(writtenStr).To(ContainSubstring("license_key: 'YOUR_LICENSE_KEY_HERE'"))
			Expect(writtenStr).NotTo(ContainSubstring("<%="))
		})

		It("should not overwrite existing config", func() {
			err := os.MkdirAll(agentDir, 0755)
			Expect(err).NotTo(HaveOccurred())

			configPath := filepath.Join(agentDir, "newrelic.yml")
			userConfig := "# User-provided configuration\nlicense_key: 'my-custom-key'\n"
			err = os.WriteFile(configPath, []byte(userConfig), 0644)
			Expect(err).NotTo(HaveOccurred())

			_, err = os.Stat(configPath)
			Expect(err).NotTo(HaveOccurred(), "Should have detected existing config file")

			existingData, err := os.ReadFile(configPath)
			Expect(err).NotTo(HaveOccurred())

			existingStr := string(existingData)
			Expect(existingStr).To(ContainSubstring("# User-provided configuration"))
			Expect(existingStr).To(ContainSubstring("my-custom-key"))
		})
	})
})
